/**
 * Canonical country list with flagcdn image URLs (40px width).
 * `name` values must match the backend's TeamMember.countryName / Representative country fields
 * exactly (e.g. "Guinea", "Republic of the Congo") so lookups by name succeed.
 */
export const COUNTRIES_WITH_FLAGS = [
  { code: 'ad', name: 'Andorra', flag: 'https://flagcdn.com/w40/ad.png' },
  { code: 'ae', name: 'United Arab Emirates', flag: 'https://flagcdn.com/w40/ae.png' },
  { code: 'af', name: 'Afghanistan', flag: 'https://flagcdn.com/w40/af.png' },
  { code: 'ag', name: 'Antigua and Barbuda', flag: 'https://flagcdn.com/w40/ag.png' },
  { code: 'ai', name: 'Anguilla', flag: 'https://flagcdn.com/w40/ai.png' },
  { code: 'al', name: 'Albania', flag: 'https://flagcdn.com/w40/al.png' },
  { code: 'am', name: 'Armenia', flag: 'https://flagcdn.com/w40/am.png' },
  { code: 'ao', name: 'Angola', flag: 'https://flagcdn.com/w40/ao.png' },
  { code: 'aq', name: 'Antarctica', flag: 'https://flagcdn.com/w40/aq.png' },
  { code: 'ar', name: 'Argentina', flag: 'https://flagcdn.com/w40/ar.png' },
  { code: 'as', name: 'American Samoa', flag: 'https://flagcdn.com/w40/as.png' },
  { code: 'at', name: 'Austria', flag: 'https://flagcdn.com/w40/at.png' },
  { code: 'au', name: 'Australia', flag: 'https://flagcdn.com/w40/au.png' },
  { code: 'aw', name: 'Aruba', flag: 'https://flagcdn.com/w40/aw.png' },
  { code: 'ax', name: 'Åland Islands', flag: 'https://flagcdn.com/w40/ax.png' },
  { code: 'az', name: 'Azerbaijan', flag: 'https://flagcdn.com/w40/az.png' },
  { code: 'ba', name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w40/ba.png' },
  { code: 'bb', name: 'Barbados', flag: 'https://flagcdn.com/w40/bb.png' },
  { code: 'bd', name: 'Bangladesh', flag: 'https://flagcdn.com/w40/bd.png' },
  { code: 'be', name: 'Belgium', flag: 'https://flagcdn.com/w40/be.png' },
  { code: 'bf', name: 'Burkina Faso', flag: 'https://flagcdn.com/w40/bf.png' },
  { code: 'bg', name: 'Bulgaria', flag: 'https://flagcdn.com/w40/bg.png' },
  { code: 'bh', name: 'Bahrain', flag: 'https://flagcdn.com/w40/bh.png' },
  { code: 'bi', name: 'Burundi', flag: 'https://flagcdn.com/w40/bi.png' },
  { code: 'bj', name: 'Benin', flag: 'https://flagcdn.com/w40/bj.png' },
  { code: 'bl', name: 'Saint Barthélemy', flag: 'https://flagcdn.com/w40/bl.png' },
  { code: 'bm', name: 'Bermuda', flag: 'https://flagcdn.com/w40/bm.png' },
  { code: 'bn', name: 'Brunei', flag: 'https://flagcdn.com/w40/bn.png' },
  { code: 'bo', name: 'Bolivia', flag: 'https://flagcdn.com/w40/bo.png' },
  { code: 'bq', name: 'Caribbean Netherlands', flag: 'https://flagcdn.com/w40/bq.png' },
  { code: 'br', name: 'Brazil', flag: 'https://flagcdn.com/w40/br.png' },
  { code: 'bs', name: 'Bahamas', flag: 'https://flagcdn.com/w40/bs.png' },
  { code: 'bt', name: 'Bhutan', flag: 'https://flagcdn.com/w40/bt.png' },
  { code: 'bv', name: 'Bouvet Island', flag: 'https://flagcdn.com/w40/bv.png' },
  { code: 'bw', name: 'Botswana', flag: 'https://flagcdn.com/w40/bw.png' },
  { code: 'by', name: 'Belarus', flag: 'https://flagcdn.com/w40/by.png' },
  { code: 'bz', name: 'Belize', flag: 'https://flagcdn.com/w40/bz.png' },
  { code: 'ca', name: 'Canada', flag: 'https://flagcdn.com/w40/ca.png' },
  { code: 'cc', name: 'Cocos (Keeling) Islands', flag: 'https://flagcdn.com/w40/cc.png' },
  { code: 'cd', name: 'DR Congo', flag: 'https://flagcdn.com/w40/cd.png' },
  { code: 'cf', name: 'Central African Republic', flag: 'https://flagcdn.com/w40/cf.png' },
  { code: 'cg', name: 'Republic of the Congo', flag: 'https://flagcdn.com/w40/cg.png' },
  { code: 'ch', name: 'Switzerland', flag: 'https://flagcdn.com/w40/ch.png' },
  { code: 'ck', name: 'Cook Islands', flag: 'https://flagcdn.com/w40/ck.png' },
  { code: 'cl', name: 'Chile', flag: 'https://flagcdn.com/w40/cl.png' },
  { code: 'cm', name: 'Cameroon', flag: 'https://flagcdn.com/w40/cm.png' },
  { code: 'cn', name: 'China', flag: 'https://flagcdn.com/w40/cn.png' },
  { code: 'co', name: 'Colombia', flag: 'https://flagcdn.com/w40/co.png' },
  { code: 'cr', name: 'Costa Rica', flag: 'https://flagcdn.com/w40/cr.png' },
  { code: 'cu', name: 'Cuba', flag: 'https://flagcdn.com/w40/cu.png' },
  { code: 'cv', name: 'Cape Verde', flag: 'https://flagcdn.com/w40/cv.png' },
  { code: 'cw', name: 'Curaçao', flag: 'https://flagcdn.com/w40/cw.png' },
  { code: 'cx', name: 'Christmas Island', flag: 'https://flagcdn.com/w40/cx.png' },
  { code: 'cy', name: 'Cyprus', flag: 'https://flagcdn.com/w40/cy.png' },
  { code: 'cz', name: 'Czechia', flag: 'https://flagcdn.com/w40/cz.png' },
  { code: 'de', name: 'Germany', flag: 'https://flagcdn.com/w40/de.png' },
  { code: 'dj', name: 'Djibouti', flag: 'https://flagcdn.com/w40/dj.png' },
  { code: 'dk', name: 'Denmark', flag: 'https://flagcdn.com/w40/dk.png' },
  { code: 'dm', name: 'Dominica', flag: 'https://flagcdn.com/w40/dm.png' },
  { code: 'do', name: 'Dominican Republic', flag: 'https://flagcdn.com/w40/do.png' },
  { code: 'dz', name: 'Algeria', flag: 'https://flagcdn.com/w40/dz.png' },
  { code: 'ec', name: 'Ecuador', flag: 'https://flagcdn.com/w40/ec.png' },
  { code: 'ee', name: 'Estonia', flag: 'https://flagcdn.com/w40/ee.png' },
  { code: 'eg', name: 'Egypt', flag: 'https://flagcdn.com/w40/eg.png' },
  { code: 'eh', name: 'Western Sahara', flag: 'https://flagcdn.com/w40/eh.png' },
  { code: 'er', name: 'Eritrea', flag: 'https://flagcdn.com/w40/er.png' },
  { code: 'es', name: 'Spain', flag: 'https://flagcdn.com/w40/es.png' },
  { code: 'et', name: 'Ethiopia', flag: 'https://flagcdn.com/w40/et.png' },
  { code: 'eu', name: 'European Union', flag: 'https://flagcdn.com/w40/eu.png' },
  { code: 'fi', name: 'Finland', flag: 'https://flagcdn.com/w40/fi.png' },
  { code: 'fj', name: 'Fiji', flag: 'https://flagcdn.com/w40/fj.png' },
  { code: 'fk', name: 'Falkland Islands', flag: 'https://flagcdn.com/w40/fk.png' },
  { code: 'fm', name: 'Micronesia', flag: 'https://flagcdn.com/w40/fm.png' },
  { code: 'fo', name: 'Faroe Islands', flag: 'https://flagcdn.com/w40/fo.png' },
  { code: 'fr', name: 'France', flag: 'https://flagcdn.com/w40/fr.png' },
  { code: 'ga', name: 'Gabon', flag: 'https://flagcdn.com/w40/ga.png' },
  { code: 'gb', name: 'United Kingdom', flag: 'https://flagcdn.com/w40/gb.png' },
  { code: 'gd', name: 'Grenada', flag: 'https://flagcdn.com/w40/gd.png' },
  { code: 'ge', name: 'Georgia', flag: 'https://flagcdn.com/w40/ge.png' },
  { code: 'gf', name: 'French Guiana', flag: 'https://flagcdn.com/w40/gf.png' },
  { code: 'gg', name: 'Guernsey', flag: 'https://flagcdn.com/w40/gg.png' },
  { code: 'gh', name: 'Ghana', flag: 'https://flagcdn.com/w40/gh.png' },
  { code: 'gi', name: 'Gibraltar', flag: 'https://flagcdn.com/w40/gi.png' },
  { code: 'gl', name: 'Greenland', flag: 'https://flagcdn.com/w40/gl.png' },
  { code: 'gm', name: 'Gambia', flag: 'https://flagcdn.com/w40/gm.png' },
  { code: 'gn', name: 'Guinea', flag: 'https://flagcdn.com/w40/gn.png' },
  { code: 'gp', name: 'Guadeloupe', flag: 'https://flagcdn.com/w40/gp.png' },
  { code: 'gq', name: 'Equatorial Guinea', flag: 'https://flagcdn.com/w40/gq.png' },
  { code: 'gr', name: 'Greece', flag: 'https://flagcdn.com/w40/gr.png' },
  { code: 'gs', name: 'South Georgia', flag: 'https://flagcdn.com/w40/gs.png' },
  { code: 'gt', name: 'Guatemala', flag: 'https://flagcdn.com/w40/gt.png' },
  { code: 'gu', name: 'Guam', flag: 'https://flagcdn.com/w40/gu.png' },
  { code: 'gw', name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w40/gw.png' },
  { code: 'gy', name: 'Guyana', flag: 'https://flagcdn.com/w40/gy.png' },
  { code: 'hk', name: 'Hong Kong', flag: 'https://flagcdn.com/w40/hk.png' },
  { code: 'hm', name: 'Heard Island and McDonald Islands', flag: 'https://flagcdn.com/w40/hm.png' },
  { code: 'hn', name: 'Honduras', flag: 'https://flagcdn.com/w40/hn.png' },
  { code: 'hr', name: 'Croatia', flag: 'https://flagcdn.com/w40/hr.png' },
  { code: 'ht', name: 'Haiti', flag: 'https://flagcdn.com/w40/ht.png' },
  { code: 'hu', name: 'Hungary', flag: 'https://flagcdn.com/w40/hu.png' },
  { code: 'id', name: 'Indonesia', flag: 'https://flagcdn.com/w40/id.png' },
  { code: 'ie', name: 'Ireland', flag: 'https://flagcdn.com/w40/ie.png' },
  { code: 'il', name: 'Israel', flag: 'https://flagcdn.com/w40/il.png' },
  { code: 'im', name: 'Isle of Man', flag: 'https://flagcdn.com/w40/im.png' },
  { code: 'in', name: 'India', flag: 'https://flagcdn.com/w40/in.png' },
  { code: 'io', name: 'British Indian Ocean Territory', flag: 'https://flagcdn.com/w40/io.png' },
  { code: 'iq', name: 'Iraq', flag: 'https://flagcdn.com/w40/iq.png' },
  { code: 'ir', name: 'Iran', flag: 'https://flagcdn.com/w40/ir.png' },
  { code: 'is', name: 'Iceland', flag: 'https://flagcdn.com/w40/is.png' },
  { code: 'it', name: 'Italy', flag: 'https://flagcdn.com/w40/it.png' },
  { code: 'je', name: 'Jersey', flag: 'https://flagcdn.com/w40/je.png' },
  { code: 'jm', name: 'Jamaica', flag: 'https://flagcdn.com/w40/jm.png' },
  { code: 'jo', name: 'Jordan', flag: 'https://flagcdn.com/w40/jo.png' },
  { code: 'jp', name: 'Japan', flag: 'https://flagcdn.com/w40/jp.png' },
  { code: 'ke', name: 'Kenya', flag: 'https://flagcdn.com/w40/ke.png' },
  { code: 'kg', name: 'Kyrgyzstan', flag: 'https://flagcdn.com/w40/kg.png' },
  { code: 'kh', name: 'Cambodia', flag: 'https://flagcdn.com/w40/kh.png' },
  { code: 'ki', name: 'Kiribati', flag: 'https://flagcdn.com/w40/ki.png' },
  { code: 'km', name: 'Comoros', flag: 'https://flagcdn.com/w40/km.png' },
  { code: 'kn', name: 'Saint Kitts and Nevis', flag: 'https://flagcdn.com/w40/kn.png' },
  { code: 'kp', name: 'North Korea', flag: 'https://flagcdn.com/w40/kp.png' },
  { code: 'kr', name: 'South Korea', flag: 'https://flagcdn.com/w40/kr.png' },
  { code: 'kw', name: 'Kuwait', flag: 'https://flagcdn.com/w40/kw.png' },
  { code: 'ky', name: 'Cayman Islands', flag: 'https://flagcdn.com/w40/ky.png' },
  { code: 'kz', name: 'Kazakhstan', flag: 'https://flagcdn.com/w40/kz.png' },
  { code: 'la', name: 'Laos', flag: 'https://flagcdn.com/w40/la.png' },
  { code: 'lb', name: 'Lebanon', flag: 'https://flagcdn.com/w40/lb.png' },
  { code: 'lc', name: 'Saint Lucia', flag: 'https://flagcdn.com/w40/lc.png' },
  { code: 'li', name: 'Liechtenstein', flag: 'https://flagcdn.com/w40/li.png' },
  { code: 'lk', name: 'Sri Lanka', flag: 'https://flagcdn.com/w40/lk.png' },
  { code: 'lr', name: 'Liberia', flag: 'https://flagcdn.com/w40/lr.png' },
  { code: 'ls', name: 'Lesotho', flag: 'https://flagcdn.com/w40/ls.png' },
  { code: 'lt', name: 'Lithuania', flag: 'https://flagcdn.com/w40/lt.png' },
  { code: 'lu', name: 'Luxembourg', flag: 'https://flagcdn.com/w40/lu.png' },
  { code: 'lv', name: 'Latvia', flag: 'https://flagcdn.com/w40/lv.png' },
  { code: 'ly', name: 'Libya', flag: 'https://flagcdn.com/w40/ly.png' },
  { code: 'ma', name: 'Morocco', flag: 'https://flagcdn.com/w40/ma.png' },
  { code: 'mc', name: 'Monaco', flag: 'https://flagcdn.com/w40/mc.png' },
  { code: 'md', name: 'Moldova', flag: 'https://flagcdn.com/w40/md.png' },
  { code: 'me', name: 'Montenegro', flag: 'https://flagcdn.com/w40/me.png' },
  { code: 'mf', name: 'Saint Martin', flag: 'https://flagcdn.com/w40/mf.png' },
  { code: 'mg', name: 'Madagascar', flag: 'https://flagcdn.com/w40/mg.png' },
  { code: 'mh', name: 'Marshall Islands', flag: 'https://flagcdn.com/w40/mh.png' },
  { code: 'mk', name: 'North Macedonia', flag: 'https://flagcdn.com/w40/mk.png' },
  { code: 'ml', name: 'Mali', flag: 'https://flagcdn.com/w40/ml.png' },
  { code: 'mm', name: 'Myanmar', flag: 'https://flagcdn.com/w40/mm.png' },
  { code: 'mn', name: 'Mongolia', flag: 'https://flagcdn.com/w40/mn.png' },
  { code: 'mo', name: 'Macau', flag: 'https://flagcdn.com/w40/mo.png' },
  { code: 'mp', name: 'Northern Mariana Islands', flag: 'https://flagcdn.com/w40/mp.png' },
  { code: 'mq', name: 'Martinique', flag: 'https://flagcdn.com/w40/mq.png' },
  { code: 'mr', name: 'Mauritania', flag: 'https://flagcdn.com/w40/mr.png' },
  { code: 'ms', name: 'Montserrat', flag: 'https://flagcdn.com/w40/ms.png' },
  { code: 'mt', name: 'Malta', flag: 'https://flagcdn.com/w40/mt.png' },
  { code: 'mu', name: 'Mauritius', flag: 'https://flagcdn.com/w40/mu.png' },
  { code: 'mv', name: 'Maldives', flag: 'https://flagcdn.com/w40/mv.png' },
  { code: 'mw', name: 'Malawi', flag: 'https://flagcdn.com/w40/mw.png' },
  { code: 'mx', name: 'Mexico', flag: 'https://flagcdn.com/w40/mx.png' },
  { code: 'my', name: 'Malaysia', flag: 'https://flagcdn.com/w40/my.png' },
  { code: 'mz', name: 'Mozambique', flag: 'https://flagcdn.com/w40/mz.png' },
  { code: 'na', name: 'Namibia', flag: 'https://flagcdn.com/w40/na.png' },
  { code: 'nc', name: 'New Caledonia', flag: 'https://flagcdn.com/w40/nc.png' },
  { code: 'ne', name: 'Niger', flag: 'https://flagcdn.com/w40/ne.png' },
  { code: 'nf', name: 'Norfolk Island', flag: 'https://flagcdn.com/w40/nf.png' },
  { code: 'ng', name: 'Nigeria', flag: 'https://flagcdn.com/w40/ng.png' },
  { code: 'ni', name: 'Nicaragua', flag: 'https://flagcdn.com/w40/ni.png' },
  { code: 'nl', name: 'Netherlands', flag: 'https://flagcdn.com/w40/nl.png' },
  { code: 'no', name: 'Norway', flag: 'https://flagcdn.com/w40/no.png' },
  { code: 'np', name: 'Nepal', flag: 'https://flagcdn.com/w40/np.png' },
  { code: 'nr', name: 'Nauru', flag: 'https://flagcdn.com/w40/nr.png' },
  { code: 'nu', name: 'Niue', flag: 'https://flagcdn.com/w40/nu.png' },
  { code: 'nz', name: 'New Zealand', flag: 'https://flagcdn.com/w40/nz.png' },
  { code: 'om', name: 'Oman', flag: 'https://flagcdn.com/w40/om.png' },
  { code: 'pa', name: 'Panama', flag: 'https://flagcdn.com/w40/pa.png' },
  { code: 'pe', name: 'Peru', flag: 'https://flagcdn.com/w40/pe.png' },
  { code: 'pf', name: 'French Polynesia', flag: 'https://flagcdn.com/w40/pf.png' },
  { code: 'pg', name: 'Papua New Guinea', flag: 'https://flagcdn.com/w40/pg.png' },
  { code: 'ph', name: 'Philippines', flag: 'https://flagcdn.com/w40/ph.png' },
  { code: 'pk', name: 'Pakistan', flag: 'https://flagcdn.com/w40/pk.png' },
  { code: 'pl', name: 'Poland', flag: 'https://flagcdn.com/w40/pl.png' },
  { code: 'pm', name: 'Saint Pierre and Miquelon', flag: 'https://flagcdn.com/w40/pm.png' },
  { code: 'pn', name: 'Pitcairn Islands', flag: 'https://flagcdn.com/w40/pn.png' },
  { code: 'pr', name: 'Puerto Rico', flag: 'https://flagcdn.com/w40/pr.png' },
  { code: 'ps', name: 'Palestine', flag: 'https://flagcdn.com/w40/ps.png' },
  { code: 'pt', name: 'Portugal', flag: 'https://flagcdn.com/w40/pt.png' },
  { code: 'pw', name: 'Palau', flag: 'https://flagcdn.com/w40/pw.png' },
  { code: 'py', name: 'Paraguay', flag: 'https://flagcdn.com/w40/py.png' },
  { code: 'qa', name: 'Qatar', flag: 'https://flagcdn.com/w40/qa.png' },
  { code: 're', name: 'Réunion', flag: 'https://flagcdn.com/w40/re.png' },
  { code: 'ro', name: 'Romania', flag: 'https://flagcdn.com/w40/ro.png' },
  { code: 'rs', name: 'Serbia', flag: 'https://flagcdn.com/w40/rs.png' },
  { code: 'ru', name: 'Russia', flag: 'https://flagcdn.com/w40/ru.png' },
  { code: 'rw', name: 'Rwanda', flag: 'https://flagcdn.com/w40/rw.png' },
  { code: 'sa', name: 'Saudi Arabia', flag: 'https://flagcdn.com/w40/sa.png' },
  { code: 'sb', name: 'Solomon Islands', flag: 'https://flagcdn.com/w40/sb.png' },
  { code: 'sc', name: 'Seychelles', flag: 'https://flagcdn.com/w40/sc.png' },
  { code: 'sd', name: 'Sudan', flag: 'https://flagcdn.com/w40/sd.png' },
  { code: 'se', name: 'Sweden', flag: 'https://flagcdn.com/w40/se.png' },
  { code: 'sg', name: 'Singapore', flag: 'https://flagcdn.com/w40/sg.png' },
  { code: 'sh', name: 'Saint Helena, Ascension and Tristan da Cunha', flag: 'https://flagcdn.com/w40/sh.png' },
  { code: 'si', name: 'Slovenia', flag: 'https://flagcdn.com/w40/si.png' },
  { code: 'sj', name: 'Svalbard and Jan Mayen', flag: 'https://flagcdn.com/w40/sj.png' },
  { code: 'sk', name: 'Slovakia', flag: 'https://flagcdn.com/w40/sk.png' },
  { code: 'sl', name: 'Sierra Leone', flag: 'https://flagcdn.com/w40/sl.png' },
  { code: 'sm', name: 'San Marino', flag: 'https://flagcdn.com/w40/sm.png' },
  { code: 'sn', name: 'Senegal', flag: 'https://flagcdn.com/w40/sn.png' },
  { code: 'so', name: 'Somalia', flag: 'https://flagcdn.com/w40/so.png' },
  { code: 'sr', name: 'Suriname', flag: 'https://flagcdn.com/w40/sr.png' },
  { code: 'ss', name: 'South Sudan', flag: 'https://flagcdn.com/w40/ss.png' },
  { code: 'st', name: 'São Tomé and Príncipe', flag: 'https://flagcdn.com/w40/st.png' },
  { code: 'sv', name: 'El Salvador', flag: 'https://flagcdn.com/w40/sv.png' },
  { code: 'sx', name: 'Sint Maarten', flag: 'https://flagcdn.com/w40/sx.png' },
  { code: 'sy', name: 'Syria', flag: 'https://flagcdn.com/w40/sy.png' },
  { code: 'sz', name: 'Eswatini (Swaziland)', flag: 'https://flagcdn.com/w40/sz.png' },
  { code: 'tc', name: 'Turks and Caicos Islands', flag: 'https://flagcdn.com/w40/tc.png' },
  { code: 'td', name: 'Chad', flag: 'https://flagcdn.com/w40/td.png' },
  { code: 'tf', name: 'French Southern and Antarctic Lands', flag: 'https://flagcdn.com/w40/tf.png' },
  { code: 'tg', name: 'Togo', flag: 'https://flagcdn.com/w40/tg.png' },
  { code: 'th', name: 'Thailand', flag: 'https://flagcdn.com/w40/th.png' },
  { code: 'tj', name: 'Tajikistan', flag: 'https://flagcdn.com/w40/tj.png' },
  { code: 'tk', name: 'Tokelau', flag: 'https://flagcdn.com/w40/tk.png' },
  { code: 'tl', name: 'Timor-Leste', flag: 'https://flagcdn.com/w40/tl.png' },
  { code: 'tm', name: 'Turkmenistan', flag: 'https://flagcdn.com/w40/tm.png' },
  { code: 'tn', name: 'Tunisia', flag: 'https://flagcdn.com/w40/tn.png' },
  { code: 'to', name: 'Tonga', flag: 'https://flagcdn.com/w40/to.png' },
  { code: 'tr', name: 'Turkey', flag: 'https://flagcdn.com/w40/tr.png' },
  { code: 'tt', name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/w40/tt.png' },
  { code: 'tv', name: 'Tuvalu', flag: 'https://flagcdn.com/w40/tv.png' },
  { code: 'tw', name: 'Taiwan', flag: 'https://flagcdn.com/w40/tw.png' },
  { code: 'tz', name: 'Tanzania', flag: 'https://flagcdn.com/w40/tz.png' },
  { code: 'ua', name: 'Ukraine', flag: 'https://flagcdn.com/w40/ua.png' },
  { code: 'ug', name: 'Uganda', flag: 'https://flagcdn.com/w40/ug.png' },
  { code: 'um', name: 'United States Minor Outlying Islands', flag: 'https://flagcdn.com/w40/um.png' },
  { code: 'un', name: 'United Nations', flag: 'https://flagcdn.com/w40/un.png' },
  { code: 'us', name: 'United States', flag: 'https://flagcdn.com/w40/us.png' },
  { code: 'uy', name: 'Uruguay', flag: 'https://flagcdn.com/w40/uy.png' },
  { code: 'uz', name: 'Uzbekistan', flag: 'https://flagcdn.com/w40/uz.png' },
  { code: 'va', name: 'Vatican City (Holy See)', flag: 'https://flagcdn.com/w40/va.png' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', flag: 'https://flagcdn.com/w40/vc.png' },
  { code: 've', name: 'Venezuela', flag: 'https://flagcdn.com/w40/ve.png' },
  { code: 'vg', name: 'British Virgin Islands', flag: 'https://flagcdn.com/w40/vg.png' },
  { code: 'vi', name: 'United States Virgin Islands', flag: 'https://flagcdn.com/w40/vi.png' },
  { code: 'vn', name: 'Vietnam', flag: 'https://flagcdn.com/w40/vn.png' },
  { code: 'vu', name: 'Vanuatu', flag: 'https://flagcdn.com/w40/vu.png' },
  { code: 'wf', name: 'Wallis and Futuna', flag: 'https://flagcdn.com/w40/wf.png' },
  { code: 'ws', name: 'Samoa', flag: 'https://flagcdn.com/w40/ws.png' },
  { code: 'xk', name: 'Kosovo', flag: 'https://flagcdn.com/w40/xk.png' },
  { code: 'ye', name: 'Yemen', flag: 'https://flagcdn.com/w40/ye.png' },
  { code: 'yt', name: 'Mayotte', flag: 'https://flagcdn.com/w40/yt.png' },
  { code: 'za', name: 'South Africa', flag: 'https://flagcdn.com/w40/za.png' },
  { code: 'zm', name: 'Zambia', flag: 'https://flagcdn.com/w40/zm.png' },
  { code: 'zw', name: 'Zimbabwe', flag: 'https://flagcdn.com/w40/zw.png' },
];
